baseURL = "https://blog.tkmngy.jp/"
languageCode = "ja"
hasCJKLanguage = true
title = "上ノ郷谷太一"
theme = "tkmngy"

[params]
  description = "デザイナー 上ノ郷谷太一 (かみのごうやたいち) のウェブサイト"
  twitter = "tchkmngy"
  author = "上ノ郷谷 太一"
  authorurl = "https://tkmngy.jp/"
  coverimage = "/apple-touch-icon-precomposed.png"
