baseURL = "https://blog.tkmngy.jp/"
languageCode = "ja"
hasCJKLanguage = true
title = "tkmngy.jp"
theme = "tkmngy"

[params]
  Description = "デザイナー 上ノ郷谷太一 (かみのごうやたいち) のウェブサイト"
  Twitter = "tchkmngy"
  Author = "上ノ郷谷 太一"
  AuthorURL = "https://tkmngy.jp/"
  CoverImage = "/apple-touch-icon-precomposed.png"
