baseURL = "https://tkmngy.jp/"
languageCode = "ja"
hasCJKLanguage = true
sectionPagesMenu = "main"
title = "上ノ郷谷太一"
theme = "tkmngy"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "概要"
    url = "/about/"
    weight = 100

  [[menu.main]]
    identifier = "posts"
    name = "随筆"
    url = "/posts/"
    weight = 110

[params]
  description = "デザイナー 上ノ郷谷太一 (かみのごうやたいち) のウェブサイト"
  twitter = "tchkmngy"
  author = "上ノ郷谷 太一"
  authorurl = "https://tkmngy.jp/"
  coverimage = "/apple-touch-icon-precomposed.png"
